### ISSUE TITLE
How to disable log output or set the output level?

### ISSUE THREAD

**Issue by duiniuluantanqin** [emiago/sipgo#102]
How to disable log output or set the output level?
```
{"level":"debug","caller":"transportlayer","network":"udp","addr":"192.168.1.100:5060","time":"2023-06-21T14:08:10+08:00","message":"getting connection"}
```

**Comment by emiago** [comment]
it is package level zerolog. Just update global zerolog logger. This is done in examples. It is still not isolated logger.

**Comment by duiniuluantanqin** [comment]
`zerolog.SetGlobalLevel(zerolog.Disabled)` 
thank you.
