### ISSUE TITLE
How UAS handles CANCEL requests

### ISSUE THREAD

**Issue by hateeyan** [emiago/sipgo#103]
Hi @emiago , now we handle CANCEL request only in `WriteResponse`.

https://github.com/emiago/sipgo/blob/cbd22c0aeab37db95454de6d2c22ac950c608c40/dialog_server.go#L299-L308

Is it better to read CANCEL in `OnCancel` handler so we can handle CANCEL request immediately.

![image](https://github.com/emiago/sipgo/assets/42289672/19917f1a-1f78-4706-b894-0263aafb34a5)

**Comment by emiago** [comment]
@hateeyan It is transaction cancel. In this case we have to create listener once dialog is created. This leads to additional goroutine. I will have to evaluate this, but idea is that you have 
ctx := dialog.Context() 

When this gets terminated, ctx is canceled.

Thanks for reporting, seems like I did no played enough with API.

**Comment by hateeyan** [comment]
@emiago Thanks for your project.

My current solution is to handle the CANCEL request in my own goroutine:
```go
	uas := dialogServer.ReadInvite(req, uasTx)

	go func() {
		for {
		    select {
		    case s:= <-uas.State():
			    // do something
		    case cancel := <-uasTx.Cancels():
			    // respond 200 to CANCEL
			    // respond 487 to INVITE
		    }
		}	
	}()
```

**Comment by emiago** [comment]
Now no more handling Cancel. It is refactored to be closer to RFC.  

ServerTransaction -> Receive Cancel -> Terminates -> Dialog detect -> Dialog Context Done. 
Last part is still some workarround, until we test more.

Cancelation on client is now done more correctly, but only via dialog. 
Transaction states are refactored

**Comment by emiago** [comment]
@hateeyan maybe check behavior on latest main. You should not handle anymore Cancelation.
