### ISSUE TITLE
[BUG] DialogClientSession.WaitAnswer() probably handles cancellation incorrectly.

### ISSUE THREAD

**Issue by yallxe** [emiago/sipgo#105]
When using WaitAnswer like this:
```go
err := sess.WaitAnswer(ctx, sipgo.AnswerOptions{ ... })
```
I tried to cancel `ctx`, but it seems not to handle it properly:
```
Jul  4 21:54:50.769408 INF transactionLayer > Unhandled sip response. UnhandledResponseHandler handler not added msg="response status=200 reason=canceling transport=UDP source=[HIDDEN]:5060"
Jul  4 21:54:50.843383 INF transactionLayer > Unhandled sip response. UnhandledResponseHandler handler not added msg="response status=487 reason=Request cancelled transport=UDP source=[HIDDEN]:5060"
Jul  4 21:54:51.377086 INF transactionLayer > Unhandled sip response. UnhandledResponseHandler handler not added msg="response status=487 reason=Request cancelled transport=UDP source=[HIDDEN]:5060"
Jul  4 21:54:52.378271 INF transactionLayer > Unhandled sip response. UnhandledResponseHandler handler not added msg="response status=487 reason=Request cancelled transport=UDP source=[HIDDEN]:5060"
Jul  4 21:54:54.382407 INF transactionLayer > Unhandled sip response. UnhandledResponseHandler handler not added msg="response status=487 reason=Request cancelled transport=UDP source=[HIDDEN]:5060"
Jul  4 21:54:58.540397 INF transactionLayer > Unhandled sip response. UnhandledResponseHandler handler not added msg="response status=487 reason=Request cancelled transport=UDP source=[HIDDEN]:5060"
``` 
Invite transaction seems to be terminated right after cancellation, however there are more messages regarding current dialog incoming.

**Comment by emiago** [comment]
@yallxe could be case that we are not waiting transaction termination, instead terminating always. 
It would be nice to see this with SIP trace and have test to cover the case

**Comment by yallxe** [comment]
Hi, sorry for the delay. I am probably not able to provide pcap file now, but I can send a visualisation of SIP flow if this will be enough.
![image](https://github.com/user-attachments/assets/ac310769-51cc-4bfc-b7e7-6e133a73d9cb)
The ACK present here was sent right after `WaitAnswer(...)` finished execution, using `sess.Ack(context.Background))`

**Comment by emiago** [comment]
@yallxe I took some time to look. ACK is here wrong. So you should get ctx cancelation error. Please check with `main`

**Comment by yallxe** [comment]
Everything seems to be working fine now. Although I have concerns on these lines
https://github.com/emiago/sipgo/blob/7fd2f42f16c9876277491e9cd018cb41a72ff5ed/dialog_client.go#L362-L368

Shouldn't InviteResponse be set before OnResponse call? If OnResponse returns an error, InviteResponse might be nil, leading to possible panics when using the response.

**Comment by emiago** [comment]
@yallxe This was just helper for caller, to abort and even to return error to itself, or just read. 
I see your concerns, but I have to evaluate. Maybe opening issue would be great. Pls close this one
