### ISSUE TITLE
ACK Handling Issue with SIP 200 OK Response

### ISSUE THREAD

**Issue by moksh-samespace** [emiago/sipgo#108]
After receiving a 200 OK response from my INVITE, I use the req and reply objects to generate the ACK using NewAckRequest. Although the ACK request is formed and relayed, I observe the retransmission of the 200 OK response on the SIP side. The following log is recorded:

`{"level":"info","caller":"transactionLayer","msg":"response status=200 reason=OK transport=UDP source=203.153.53.161:5060","time":"2024-07-20T20:16:36Z","message":"Unhandled sip response. UnhandledResponseHandler handler not added"}`

**Comment by emiago** [comment]
easier is to use `DialogClient` but I have not  info here to debug. Obviously ACK is either malformed or not reached endpoint. This ACK has specific behavior (non transactional). 
I suggest check how `DialogClient` does it.
