### ISSUE TITLE
Documentation Improvements for emiago/sipgo: Enhancing Clarity for New Developers.

### ISSUE THREAD

**Issue by Snehashish06** [emiago/sipgo#112]
I recently started exploring emiago/sipgo library as a new Go developer. 
 
 While the library itself seems promising, I found the documentation to be somewhat challenging for beginners. It lacks detailed explanations and examples, making it hard to grasp certain concepts.

Specifically, I’m interested in understanding how to perform tasks like sending calls, recording conversations, handling DTMF responses, and potentially detecting machine-generated calls. Although I managed make a call and to end a call by storing the dialog variable, I believe there might be more efficient ways to achieve this.

I kindly request that the documentation be enhanced with clearer explanations, practical examples, and perhaps some best practices for common use cases. This would greatly benefit new developers like myself who are eager to leverage this library effectively.

**Thank you for your attention!**

**Comment by emiago** [comment]
Hi @Snehashish06. You are asking something different that glues all together, which may soon be available. I can not promise yet or give timeline, but it will be soon.

**Comment by Snehashish06** [comment]
Hey @emiago, 
Thanks for the update! I'm eager to hear more about emiago/sipgo. Could you point me in the right direction to learn more about it? I've been searching for a library like this one that's regularly updated and well-maintained.

Your help is much appreciated. Thanks for taking the time to share with me!

**Comment by emiago** [comment]
Hi @Snehashish06 . As I mentioned new project is comming up. Call it framework but it is more library. 
This will be more documented as you can build workable production code, as shown here https://emiago.github.io/diago/
With this project you can start building media servers and if needed go deeper into media and SIP. 

If you are building something else with just SIP (proxies), I think that you need follow just SIP RFC.  SIPgo is exposing RFC stuff in correct way, but there is more to follow.
With **diago** there is chance to have this also part of lib and not just dealing with dialogs. For example registrar.

I may share more info once it gets OS.
