### ISSUE TITLE
 Unhandled sip response for SIP INFO Event

### ISSUE THREAD

**Issue by p-akshay** [emiago/sipgo#118]
Hello,

I am executing the following scenario:

1. User A sends INVITE to SIP Server ... both client and server are based on sipgo ... assume that the CSeq of this INVITE is 5
2. SIP Server forwards the INVITE to requested User B and upon receiving 200 OK, sends 200 OK back to User A
3. This transaction is concluded when SIP Server receives ACK from User A ... CSeq is still 5 
4. Now, the SIP Server and User A want to exchange some information related to the call and use SIP INFO for this purpose...here the CSeq is used in increasing order (so initially it is 6, then 7 and so on)...also the SIP INFO shared was via call Dialog 
5. When the other endpoint responds to SIP INFO with 200 OK, I observe the following error

`transactionLayer > Unhandled sip response. UnhandledResponseHandler handler not added msg="response status=200 reason=OK transport=WSS`

I think the expected behavior should be that the received 200 OK is accepted (as it is done in case of other sip events)

Let me know, if you need logs and any other info, i can add those separately 

Thanks

**Comment by emiago** [comment]
Not sure, I would need some sip traces to check. It is like your transaction was terminated

**Comment by emiago** [comment]
Hi @p-akshay I think lately dialog handling API is lot improved. Can you still replicate this behavior.
I suggest if you are building B2BUA system that you switch to diago project and give feedback there. 

Still this could be sipgo issue with dialog requeest handling.

So what I need is:
- Forwards means 3xx response or new dialog request like B2BUA?

It is not clear are you building B2BUA or proxy behavior.

**Comment by p-akshay** [comment]
Hi @emiago ,

in version 0.23, the issues are not observed frequently compared to previous versions.
Unfortunately, as it is not frequent, I do not have full debug logs for the same.

I am building a B2BUA type system.


I will close the issue for now...I will open the issue again if I can get full logs. 

Thanks for the upgrade...it has resolved most of the cases.
