### ISSUE TITLE
DNS Resolution Error in case of WSS based SIP Transaction

### ISSUE THREAD

**Issue by p-akshay** [emiago/sipgo#119]
Hello,

I am working on a system where my SIP Server is on AWS.
in my setup, I have "A Record" mapping of "ims.xxxx.in" as the domain-name to "65.2.x.x" IP address. 

On most networks, I can use my SIP Server from my client via forwarding the packet to "ims.xxxx.in" and using the WSS as the transport.

However, there are few networks, where this server is not accessible as the SIP request to server timeouts.
Upon further investigation, what I found is as following:

1. If we do `net.LookupIP("ims.xxxx.in")` on a problem network and print the results then, we receive the following: 
`IP address: 64:ff9b::4102:xxxx
IP address: 65.2.x.x`

2. Looking at sipgo transport-related code, I can see that the function "resolveAddrIP()" used for DNS lookup, returns the 1st IP address found for the given host.
3. In my scenario, since the 1st IP address is of type IPv6 (actually IPv4 represented in IPv6 Format), and it is not directly mapped to the given host, I think all the SIP transactions are timing out.

Is there a way to solve this issue? like can we do some kind of cascading type IP address pickup here?
Or can we put some kind of restrictions for looking for IPv4 addresses only?

Any suggestion will be helpful.

Thanks

**Comment by emiago** [comment]
Hi @p-akshay, currently not solvable. We could btw extend resolver behavior. Unfortunately go resolver is not much configurable, so it would require wrapper.

**Comment by emiago** [comment]
Anyway this is something that will be addressed more. I suggest going with some temporarly fix. It can be option on transport layer. Give me some time to add it.
For example DNSAddrFilter(hostname string, []net.IP) []net.IP

**Comment by p-akshay** [comment]
Hi @emiago ,

Ok...noted...

I am using a temporary workaround where I check if the resolved IP address is IPv4 or not and use the correct one.

Thanks for the explanation.
If you want, I can close the Issue.

Regards

**Comment by emiago** [comment]
@p-akshay this is now forced to be IPV4. I would consider your issue is fixed, but we still need better way to solve.

**Comment by p-akshay** [comment]
Ok Thanks

will test and confirm
