### ISSUE TITLE
Unable to receive Cancel for Invite

### ISSUE THREAD

**Issue by moksh-samespace** [emiago/sipgo#122]
<img width="419" alt="Screenshot 2024-08-15 at 2 44 24 AM" src="https://github.com/user-attachments/assets/9a1f937d-cae7-4658-87b9-ab502591ce6c">

I’m unable to receive Cancel requests within the onCancel or onInvite handlers using the following code:

`
go func() {
	for {
		select {
		case m := <-tx.Cancels():
			// handle cancel
		case m := <-tx.Acks():
			// handle ack
		case <-tx.Done():
			// handle completion
		}
	}
}()
`

**Comment by moksh-samespace** [comment]
how can I receive cancel for such incoming invite server transactions?

**Comment by emiago** [comment]
relates to #103 

@moksh-samespace try latest code. Now cancel is automatically detected and canceled for you.

**Comment by moksh-samespace** [comment]
Thanks @emiago . Will have a look at it.
