### ISSUE TITLE
Invalid value for msg.dest if IP PBX uses a proxy

### ISSUE THREAD

**Issue by Stilch** [emiago/sipgo#129]
Some IP PBX use proxy on their internal network. Which leads to the appearance of Record-Route headers in the responses.
When trying to make a call to such IP PBX, the call crashes with the error "IP addr resolving failed, doing via dns SRV resolver...".
This happens because if there are Record-Route headers, the first header is taken and set as msg.dest. This is incorrect behavior because the first header is the address of the last proxy server in the entire chain and often this address is located in a private IP PBX network.

Incorrect code section:
https://github.com/emiago/sipgo/blob/4552fe4bb49ae18fd609956b7ebd80d95f432a97/dialog_client.go#L353-L355

Example:
```SIP/2.0 183 Call progress
Via: SIP/2.0/TCP 192.168.50.154:16486;rport=16486;branch=z9hG4bKPja63ddba066b94e20a745663dd5c9f80d;alias
Record-Route: <sip:c192.168.40.77.4677453.call.cgatepro;lr>
Record-Route: <sip:212.53.10.30:5060;transport=tcp;lr>
From: <sip:4542732210@sipnet.ru>;tag=eb2e2d121eb4429c823afb28d7e07fd8
To: <sip:79634568531@sipnet.ru>;tag=B53A61D1-161225-DDECDC4B_kdcmbtp-27BC
Call-ID: d29acea6e194f0d781acdc9663bebf97
CSeq: 32203 INVITE
Contact: <sip:signode-161225-DDECDC4B_kdcmbtp-27BC@212.53.10.30>
Supported: 100rel,timer,replaces,histinfo,precondition
Allow: INVITE,BYE,CANCEL,ACK,OPTIONS,INFO,MESSAGE,PRACK,UPDATE,REFER
User-Agent: CommuniGatePro-callLeg/6.3.19
Content-Type: application/sdp
Content-Length: 226

v=0
o=CGPLeg162512 1288204518 644102260 IN IP4 212.53.10.77
s=SMG SIP session
c=IN IP4 212.53.10.77
t=0 0
m=audio 18160 RTP/AVP 8 101
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=sendrecv```

**Comment by emiago** [comment]
Correct. Will be fixed

**Comment by emiago** [comment]
Hi @Stilch 
fixed on main branch.
