### ISSUE TITLE
 10000 connect tcp/tls  issue

### ISSUE THREAD

**Issue by situnan** [emiago/sipgo#132]
The bottom layer uses the Net module, a tcp/tls connection to a goroutine, if 10000 connect will be 10000 goroutines, which is very memory intensive

**Comment by emiago** [comment]
Unless you explain this better, I am closing this. Thanks

**Comment by situnan** [comment]
we test 100000 tcp/tls client to server（no data to server,only connect）. server memory is too high.
2)then CPU occasionally high（ top -d 1 ）,reason is golang gc to (map[string]Transport)
