### ISSUE TITLE
Support for Adding Custom Headers in BYE Requests for DialogServer

### ISSUE THREAD

**Issue by BeastBeno** [emiago/sipgo#135]
While sending a BYE request, it would be beneficial if the implementation allowed the addition of custom headers, similar to how it's handled for other SIP methods.

**Comment by emiago** [comment]
hi @BeastBeno ok I now client allows `WriteBye` request. Are we speaking about dialog client or server.

**Comment by BeastBeno** [comment]
> Are we speaking about dialog client or server?

I was refering to the server

**Comment by emiago** [comment]
HI @BeastBeno ok I need to check, maybe It was not exposed, but yes you should be able to build request add headers and let dialog build missing parts.

**Comment by emiago** [comment]
fixed on main
