### ISSUE TITLE
Realm/Domain different from Host

### ISSUE THREAD

**Issue by medemi68** [emiago/sipgo#146]
Hello,

I am trying to setup sipgo so that it connects to my Freeswitch server. My freeswitch server is located at pbx.x.a.com (I've replaced part of the domain with x,a for privacy reasons), but the domain as part of the from header needs to be different from the hostname of the freeswitch server. In this case, it would be b.com for example.

This is a fairly common implementation, where the actual SIP headers point to domains that aren't real (for the purposes of authenticating a user). Where the actual communication to the sip server happens at a different address/domain.

As part of the RFC for SIP (specifically section 8.1.1.3) the realm/domain can be different. 
See here: 
https://stackoverflow.com/questions/13498356/in-a-sip-register-message-should-the-from-header-contain-a-resolvable-host-domai

The problem is, no matter what I do, sipgo seems to always try to establish a connection to b.com instead of pbx.x.a.com, because it seems to be parsing the host to connect to from the SIP URI. That is not supposed to happen. My actual sip credentials are user@b.com and the host that I need to connect to is pbx.x.a.com.

Would it be possible to add proper authentication and include realm/domain support?

**Comment by emiago** [comment]
Hi @medemi68 . Default behavior is yes, go whatever is recipient uri. 
Overriding destination is done with `SetDestination` on request. Changing From hostname can be set on UA or adding custom From Header. into request. 

As for registration auth there is some built in client. Look for DigestAuth. 
If you need more Register  working speicific solution, diago is next place to look. You can contact me on mail if you are building something more serious.
