### ISSUE TITLE
client tx errs chan may block go routinue.

### ISSUE THREAD

**Issue by yushimeng** [emiago/sipgo#15]
ClientTx.timeoutErr() may blcoked if no routinue receive errs.

**Comment by emiago** [comment]
Hi @yushimeng 
Yes generally errors passing needs to be reworked, but great for noticing.
Passing errors on chan is not good approach unless it is requested by caller. Also as they are just informative (transaction fsm will  terminate).

**Comment by emiago** [comment]
Hi @yushimeng 
I created one PR, but it needs to be retested.
Now transaction has no `chan error` instead it has now 
`Err() error`  function that can be used to check last Error. 
Mostly this are tranport or timeout err that will terminate transaction.

**Comment by emiago** [comment]
merging this
