### ISSUE TITLE
 Dialog server example  for echo rtp packet

### ISSUE THREAD

**Issue by tkang007** [emiago/sipgo#23]
Hi,
Appreciate u for all of your contributions and helps.

Could you please guide how to use  dialog server for recording and  playback the arrive rtp packet payload. say rtp payload  echo example.

I would like to streaming out/in the payload to/from an external service.

Thanks in advance.

**Comment by tkang007** [comment]
Hello,
I am trying to prepare a sip phone for bridging with an external voice service, such as STT, chatBOT, TTS.

With combining example/register/client and example/dialog,  I met below message log when calling to the registered number.

I am expecting the dialog example could be used for incoming call in SIP level(not for outgoing call - as no client dialog feature).  
Could you help me what I am missing or misunderstanding for the dialog server features ?

Thanks in advance.

```
Jun  2 12:06:21.551935 INF starting dialog serve ip=192.168.219.101:15060 srv=192.168.219.101:5060
Jun  2 12:06:21.552234 DBG transport<UDP> > begin listening on UDP 192.168.219.101:15060
Jun  2 12:06:24.552561 INF registering uri=sip:100@192.168.219.101:5060
Jun  2 12:06:24.552774 DBG transportlayer > Connection ref increment req=REGISTER
Jun  2 12:06:24.554124 DBG register received status status=401
Jun  2 12:06:24.554190 DBG transportlayer > Connection ref increment req=REGISTER
Jun  2 12:06:24.555859 INF registered uri=sip:100@192.168.219.101:5060
Jun  2 12:06:27.312899 DBG transportlayer > Connection ref increment req=INVITE
Jun  2 12:06:32.318147 DBG transaction.Layer > Destroyed tx=z9hG4bKPj25bd6870-eea6-4fe6-a227-08c34ac0667e__192.168.219.101__5060__INVITE
Jun  2 12:06:32.318474 DBG Transaction done req=INVITE
Jun  2 12:06:32.318517 DBG transaction.Layer > Destroyed tx=z9hG4bK.e9B2nIJL94XbhLJYw6EwOnRb2w7zfOfy__INVITE
Jun  2 12:06:32.318545 DBG transaction.Layer > Destroyed tx=z9hG4bKPj25bd6870-eea6-4fe6-a227-08c34ac0667e__192.168.219.101__5060__INVITE
Jun  2 12:06:56.570746 DBG transaction.Layer > Destroyed tx=z9hG4bK.O3ugHFLHNZmSlW8RkDDOmkRLPIxriE8B__REGISTER
Jun  2 12:06:56.570868 DBG transaction.Layer > Destroyed tx=z9hG4bK.siBIlzbRQRzNwLsYJYiVOtLAYlnRVLFH__REGISTER
```

**Comment by emiago** [comment]
hi @tkang007 
Currenltly it was added very experimentally but only **yes** for server side. 
This mainly could be used for some dialog tracking, but not more than that. 

I have open issue for this topic. It was asked couple of times so therefore it is there. 
https://github.com/emiago/sipgo/issues/3

In case of your first question, currently this lib does only SIP signaling (and it does it fast) but for media handling you need to see for some additional libraries for rtp, sdp. If you already had some research maybe share here. 

I would like maybe to provide some simple examples here.

**Comment by tkang007** [comment]
Thanks for your feedback!!!
