### ISSUE TITLE
Example, register/client SIGSEGV case when Algorithm in lowercase.

### ISSUE THREAD

**Issue by tkang007** [emiago/sipgo#24]
Hi,
I would like to report an issue when register to an Asterisk with the example/register/client/main.go 

```
$  ./client -ip 192.168.219.101:15060 -srv 192.168.219.101:5060 -u 100 -p 100
...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x648827]

goroutine 1 [running]:
github.com/icholy/digest.(*Credentials).String(0x0)
        /home/vagrant/go/pkg/mod/github.com/icholy/digest@v0.1.22/credentials.go:76 +0x67
main.main()
        /home/vagrant/sipgo/example/register/client/main.go:101 +0xe05
```

Could be fixed by changing Algorithm to uppercase as it was expected by digest.Digest method.
```
...
		wwwAuth := res.GetHeader("WWW-Authenticate")
		chal, err := digest.ParseChallenge(wwwAuth.Value())
		if err != nil {
			log.Fatal().Str("wwwauth", wwwAuth.Value()).Err(err).Msg("Fail to parse challenge")
		}
		chal.Algorithm = strings.ToUpper(chal.Algorithm)   //##### fixing
...
```
Asterisk's WWW-Authenticate parsed challenge: 
```
github.com/icholy/digest.Challenge {Realm: "asterisk", Domain: []string len: 0, cap: 0, nil, Nonce: "1685669327/dfd8ceb694344a6f663b95f91eb48096", Opaque: "2ac5572d63798b56", Stale: false, Algorithm: "md5", QOP: []string len: 1, cap: 1, ["auth"], Charset: "", Userhash: false}
```

Thanks.

**Comment by tkang007** [comment]
just for sharing

**Comment by emiago** [comment]
Hi @tkang007 maybe to create a PR. Not sure is some digest lib issue.

**Comment by r4hx** [comment]
Yes. It is issue belong digest. I made PR for fix it https://github.com/icholy/digest/pull/11 or you can use my fork https://github.com/r4hx/digest

You need just add to your go.mod

> replace github.com/icholy/digest => github.com/r4hx/digest v0.0.1

and run command in terminal 

> go mod tidy

**Comment by emiago** [comment]
@r4hx I only noticed this issue couple days ago and it is older version of asterisk (16). I guess they fixed on their end in newer version. 
Let me know when your PR merges

**Comment by r4hx** [comment]
> @r4hx I only noticed this issue couple days ago and it is older version of asterisk (16). I guess they fixed on their end in newer version. Let me know when your PR merges

My PR will not be merge, because maintainer reject it. He gave an another solution which more clearly (maybe, i not a golang programmer :D) and simply. But my solution still worked, we have a two tweak how to solve this problem now.

**Comment by emiago** [comment]
yes he is right about rfc. Still solution he provides seems something related to HTTP?

**Comment by r4hx** [comment]
> Still solution he provides seems something related to HTTP?

No, it’s solution related to udp (header of packet).

**Comment by emiago** [comment]
hi @r4hx fixed on client.

**Comment by r4hx** [comment]
> hi @r4hx fixed on client.

Nice work. Thank you.
