### ISSUE TITLE
Adding support for SDP parsing and encoding

### ISSUE THREAD

**Issue by emiago** [emiago/sipgo#26]
Based on #22 or #23 there could be use to have in this lib for simple SDP parsing. Manipulating SDP is needed in lot of cases.
[This needs  some research](https://datatracker.ietf.org/doc/html/rfc4566)

This is only for SDP parsing but not for media/rtp handling.

**Comment by emiago** [comment]
with SDP in place, simple echo or drop rtp can be implemented. (Could be useful for building test softphones)

**Comment by half2me** [comment]
@emiago I'd be interested in helping to add support for RFC 4574

**Comment by emiago** [comment]
hi @half2me. It would be great to have more eyes on this. 

I have started already some version
https://github.com/emiago/sipgox/blob/main/sdp.go
currently only for small client usage needs. (setuping audio). 
this can be some starter for new package.

For reference: I used also `pion/sdp` but I find it not updated and also not so simple struct.

Currently goal here is to stabilize SIP handling, so I moving all other features in sipgox for experimental.
I had no time to move this tickets as well.

**Comment by half2me** [comment]
@emiago it might make sense to make use of a library for this? For my project I've used https://github.com/pixelbender/go-sdp
There is also one by pion webrtc: https://github.com/pion/sdp

Would it make sense to just use one of these parsers instead of writing a new one?

**Comment by emiago** [comment]
Yes of course. I only knew for pion, but thanks for sharing other one. 
Seems more better approach for me. 
At least structure looks simpler. 

I wiil check it out and close ticket if find it good.

**Comment by emiago** [comment]
one more to check out
https://github.com/jart/gosip/tree/master/sdp

**Comment by arkadijs** [comment]
Also used pixelbender's sdp, now using pion.

Consider the [RFC 5621](https://www.rfc-editor.org/rfc/rfc5621.html#page-6) to support `multipart/*` INVITE-s, I'd say it's cleaner to leave message parsing to established libraries.

**Comment by half2me** [comment]
note on `pion/sdp` parser. It imposes strict requirements for the SDP. Requirements that WebRTC has, but voip does not. I'd like to give some concrete examples, but for my sample voip application it kept throwing errors when I tried to parse it, complaining about some missing fields. pixelbender sdp parsing worked without any issues for the exact same SDP.

**Comment by emiago** [comment]
@half2me that is reason why I discarded that. I still did not find time to checkout other.

**Comment by emiago** [comment]
as already obvious, SDP parsing is added on sipgox project. All development is moved there. 
For not it is very simple parsing, but anyone is welcome to extend it. validation of values and parsing must be seperated
