### ISSUE TITLE
there is some suggestion

### ISSUE THREAD

**Issue by czk630597526** [emiago/sipgo#29]
maybe we need function like this
![1689263889939](https://github.com/emiago/sipgo/assets/88134686/e658ebbb-3fc0-4905-bed1-948cbcdcf6e5)
adapt some situation ext addr is not 5060
![image](https://github.com/emiago/sipgo/assets/88134686/c6eb881f-396c-4f4c-9237-f4cfd16c6b8e)
so we can prevent the influence of record route.

**Comment by emiago** [comment]
Aah probably I introuduced a bug with latest change. 
I am still not sure with this regard.
I want to decouple client in case building just UAC.
User agent holds only IP for sharing but port number should not be fixed.
will see to provide soon some hot fix

**Comment by emiago** [comment]
@czk630597526 pls check latest changes. Using on client WithClientHostname and WithClientPort is added. 
Using ua WithUserAgentIP may now be duplicate. Generally  IP has no usage on UA level, also  setting port like this is still questionable as depends on req transport. This may change

**Comment by czk630597526** [comment]
> @czk630597526 pls check latest changes. Using on client WithClientHostname and WithClientPort is added. Using ua WithUserAgentIP may now be duplicate. Generally IP has no usage on UA level, also setting port like this is still questionable as depends on req transport. This may change

thanks for reply，This change may be the elegant solution
