### ISSUE TITLE
Does the 4** status code response also need to add a tag to the TO header?

### ISSUE THREAD

**Issue by ts0203** [emiago/sipgo#43]
Does the 4** status code response also need to add a tag to the header?

// RFC 3261 - 8.2.6
func NewResponseFromRequest(

       ........

	if statusCode == 100 {
		CopyHeaders("Timestamp", req, res)
	}

	if statusCode == 200 {
		if _, ok := res.to.Params["tag"]; !ok {
			uuid, _ := uuid.NewV4()
			res.to.Params["tag"] = uuid.String()
		}
	}
        
        ........
	
        return res
}

**Comment by ts0203** [comment]
[8.2.6.2](https://www.rfc-editor.org/rfc/rfc3261#section-8.2.6.2) Headers and Tags

   The From field of the response MUST equal the From header field of
   the request.  The Call-ID header field of the response MUST equal the
   Call-ID header field of the request.  The CSeq header field of the
   response MUST equal the CSeq field of the request.  The Via header
   field values in the response MUST equal the Via header field values
   in the request and MUST maintain the same ordering.

   If a request contained a To tag in the request, the To header field
   in the response MUST equal that of the request.  However, if the To
   header field in the request did not contain a tag, the URI in the To
   header field in the response MUST equal the URI in the To header
   field; additionally, the UAS MUST add a tag to the To header field in
   the response (with the exception of the 100 (Trying) response, in
   which a tag MAY be present).  This serves to identify the UAS that is
   responding, possibly resulting in a component of a dialog ID.  The
   same tag MUST be used for all responses to that request, both final
   and provisional (again excepting the 100 (Trying)).  Procedures for
   the generation of tags are defined in [Section 19.3](https://www.rfc-editor.org/rfc/rfc3261#section-19.3).

**Comment by ts0203** [comment]
I am not sure if this modification is correct?


	if statusCode == 100 {
		CopyHeaders("Timestamp", req, res)
	} else {
		//if statusCode == 200 {
		if _, ok := res.to.Params["tag"]; !ok {
			uuid, _ := uuid.NewV4()
			res.to.Params["tag"] = uuid.String()
		}
	}

**Comment by emiago** [comment]
@ts0203 good catch. I think you are right. Strange I did notice some errors before. 
Lets have a switch statement there, just in case some additional code handling is needed.

**Comment by ts0203** [comment]
Ok, thanks a lot for your help!

**Comment by emiago** [comment]
Fix added
