### ISSUE TITLE
Random free local port in `Client`

### ISSUE THREAD

**Issue by a12n** [emiago/sipgo#46]
Hi Emir,

Looks like zero port value in `sipgo.Client` means `sip.Default{Tcp,Udp}Port`[^1] and not "any random available port from the OS". It's a bit surprising: usually in client contexts zero/unspecified port is a way to say "I don't care about the port, choose any". E.g., standard `net.Dial{TCP,UDP}` functions work that way, [SIPp](https://sipp.sourceforge.net/) also chooses local port randomly by default (excerpt from `sipp` usage):
```
   -p               : Set the local port number.  Default is a random free port chosen by the
                      system.
```

What I would expect:
* `sipgo.NewClient(ua)` or `sipgo.NewClient(ua, sipgo.WithClientPort(0))` will use any available client port.
* `sipgo.NewClient(ua, sipgo.WithClientPort(sip.DefaultPort))` will use the registered SIP port 5060.

I'm not sure whether it's too late to make such breaking change (different meaning for zero port value). If it is, maybe add some special constant (`const AnyPort = -1`?) for `sipgo.WithClientPort`? Something like this:

```diff
diff --git a/client.go b/client.go
index 1a0a215..0792256 100644
--- a/client.go
+++ b/client.go
@@ -41,7 +41,11 @@ func WithClientHostname(hostname string) ClientOption {
 	}
 }
 
-// WithClientPort allows setting default route port
+// WithClientPort allows setting default route port.
+//
+// If zero, [sip.DefaultUdpPort] or [sip.DefaultTcpPort] will be
+// used. If -1, the client port will be chosen automatically by the
+// OS.
 func WithClientPort(port int) ClientOption {
 	return func(s *Client) error {
 		s.port = port
diff --git a/transport/tcp.go b/transport/tcp.go
index 22d4bec..1dc63b5 100644
--- a/transport/tcp.go
+++ b/transport/tcp.go
@@ -94,7 +94,10 @@ func (t *TCPTransport) CreateConnection(laddr Addr, raddr Addr, handler sip.Mess
 			Port: laddr.Port,
 		}
 
-		if tladdr.Port == 0 {
+		switch tladdr.Port {
+		case -1: // Use any available port.
+			tladdr.Port = 0
+		case 0: // Use default port.
 			tladdr.Port = sip.DefaultTcpPort
 		}
 	}
diff --git a/transport/udp.go b/transport/udp.go
index 8da541c..d112453 100644
--- a/transport/udp.go
+++ b/transport/udp.go
@@ -130,7 +130,10 @@ func (t *UDPTransport) CreateConnection(laddr Addr, raddr Addr, handler sip.Mess
 			Port: laddr.Port,
 		}
 
-		if uladdr.Port == 0 {
+		switch uladdr.Port {
+		case -1: // Use any available port.
+			uladdr.Port = 0
+		case 0: // Use default port.
 			uladdr.Port = sip.DefaultUdpPort
 		}
 	}
diff --git a/transport/ws.go b/transport/ws.go
index 168f859..6fc9177 100644
--- a/transport/ws.go
+++ b/transport/ws.go
@@ -224,7 +224,10 @@ func (t *WSTransport) CreateConnection(laddr Addr, raddr Addr, handler sip.Messa
 			Port: laddr.Port,
 		}
 
-		if tladdr.Port == 0 {
+		switch tladdr.Port {
+		case -1: // Use any available port.
+			tladdr.Port = 0
+		case 0: // Use default port.
 			tladdr.Port = sip.DefaultTcpPort
 		}
 	}
```

[^1]: It's not obvious why two distinct port constants: the port number is [the same](https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?&page=89) for UDP, TCP and SCTP transports.

**Comment by emiago** [comment]
This is something I added lately, but to handle some port i used default ones. It was some breaking change.

Fixing this on main branch. Now 0 will be any port. 
Pls test and reopen issue

Thnx for opening issue
