### ISSUE TITLE
BYE doesn't terminate transaction

### ISSUE THREAD

**Issue by half2me** [emiago/sipgo#53]
Here is an excerpt from my app using this library. I have to register the `srv.OnAck` and `srv.OnBye` otherwise they will be rejected. My issue is that after my successful sip call when the `BYE` message arrives, the `tx.Done()` channel will not fire. I've also noticed that after a timeout, regardless if I'm in the middle of a call or not, the transaction gets terminated and then the channel fires and the code runs. How can I control this behaviour? I tried doing a `tx.Terminate()` in the `BYE` handler, but even that did not work.

```go

func onBye(req *sip.Request, tx sip.ServerTransaction) {
  _ = tx.Respond(sip.NewResponseFromRequest(req, sip.StatusOK, "OK", nil))
}

func onACK(req *sip.Request, tx sip.ServerTransaction) {
  return
}

func onInvite(req *sip.Request, tx sip.ServerTransaction) {
  // ---- sdp offer & response ---
  sdpOffer, _ := sdp.Parse(req.Body())
  session, _ := engine.NewSession(*sdpOffer)
  defer engine.CloseSession(&session)
  res := sip.NewSDPResponseFromRequest(req, session.Response.Bytes())
  _ = tx.Respond(res)
  // -----------------------------

for {
  select {
  case m := <-tx.Cancels():
    // this never gets called
    _ = tx.Respond(sip.NewResponseFromRequest(m, 200, "OK", nil))
  case <-tx.Done():
    // this doesn't get called on BYE
    return
  case <-tx.Acks():
    // I've also never seen this called
    return
  }
}

func main() {
  ua, _ := sipgo.NewUA()
  srv, _ := sipgo.NewServerDialog(ua)

  srv.OnInvite(onInvite)
  srv.OnAck(onACK)
  srv.OnBye(onBye)
  if err := srv.ListenAndServe(context.TODO(), "udp", *extIP); err != nil {
    panic(err.Error())
  }
}
```

**Comment by emiago** [comment]
@half2me This has todo more with SIP protocol and understanding transaction state machine which in this case reason why you see INVITE not closing is timers behind and handling INVITE/responses retransimissions.  INVITE have special way of handling and different state transition.
https://datatracker.ietf.org/doc/html/rfc3261#section-17.2
https://www.rfc-editor.org/rfc/rfc6026#section-7.1
ACKs on 200 is different transaction (per SIP)
ACKs/Cancel on rest are on same transaction => those are channels you see

What you are probably looking is **dialog** managment which is something I am still exploring, something you can find on **sipgox** but I also have done this in `psip` tool.
We have open issue
https://github.com/emiago/sipgo/issues/28


Still all transactions should close after there timers endup.

Buidling this dialog managing is not big deal but is problem to cover all use cases and I guess you can get this easy done in your case.
There are helper func, search for something like MakeDialogID ... which helps you to map your dialog transactions.

**Comment by emiago** [comment]
Relating also to
https://github.com/emiago/sipgo/issues/47

**Comment by emiago** [comment]
@half2me Added now dialog support in lib. 
Pls check readme
