### ISSUE TITLE
Client register example - parser package not found

### ISSUE THREAD

**Issue by sthustfo1** [emiago/sipgo#60]
When trying to run register client example, get the following error

```
main.go:14:2: no required module provides package github.com/emiago/sipgo/parser; to add it:
	go get github.com/emiago/sipgo/parser
```

recipient fields can be assigned individually I guess.

Running `go mod tidy` return following

`	github.com/emiago/sipgo/parser: module github.com/emiago/sipgo@latest found (v0.15.2), but does not contain package github.com/emiago/sipgo/parser`

**Comment by emiago** [comment]
Hi @sthustfo1 

Currently there were some code restructure changes. Probably this was not updated. Will provide a fix.

**Comment by emiago** [comment]
pls update to main branch

**Comment by sthustfo1** [comment]
Thanks, working now.
