### ISSUE TITLE
func cloneRequest(req *Request) *Request { not generate new branch ID

### ISSUE THREAD

**Issue by danielchristianschroeter** [emiago/sipgo#63]
req.Clone() used in https://github.com/emiago/sipgo/blob/2a2060a05ce55642090e3407f1e056f4b3e29d6f/example/register/client/main.go#L95 does not generate new branch ID on Authorization request. Therefore the request will end up in errors like this:
```
Dec 30 19:20:35.279400 INF Received status status=401
Dec 30 19:20:35.279494 FTL Fail to create transaction error="transaction \"z9hG4bK.Bw6JZkBt28fHVwSe__REGISTER\" already exists"
```

By RFC3261, the branch ID must be unique for each new transaction.

**Comment by emiago** [comment]
Hi @danielchristianschroeter 
thnx for reporting. 

On `sipgox` there is full function for `register`. So I compared this 2.

`Clone` is request function only used for duplicating request due to pointers behind.

Issue is fixed, but also improved
