### ISSUE TITLE
Incorrect parsing of an address with both user and header parameters 

### ISSUE THREAD

**Issue by InnovativeUS** [emiago/sipgo#66]
Parsing the address:

`"Bob" <sips:bob:password@127.0.0.1:5060;user=phone>;tag=1234"`

places

`user=phone>;tag=1234` 

in the header tags.

This causes issues when responding to an INVITE, which expects the same From header back.

Pull request #67 has been submitted

**Comment by emiago** [comment]
Hi @InnovativeUS thanx for reporting. Will check it out. This could be broken due to some refactoring.

**Comment by emiago** [comment]
Thanks for contributing!

**Comment by emiago** [comment]
also now refactored to have less this control vars 
@InnovativeUS
