### ISSUE TITLE
How to send SIP MESSAGE to the registered client from sipgo server process?

### ISSUE THREAD

**Issue by p-akshay** [emiago/sipgo#71]
Hi @emiago 

First of all, thank you for your great work with this library.

I am trying this library based on my experience with FreeSWITCH
I am looking at this as mainly a server-side product.

From my client, I could register on sipgo based server successfully. 
Further, I was able to respond to any sip event received from the client with standard responses like 200OK, 403 etc.

Now I wanted to send an SIP Message from the server to an already registered user. (Initiate a new sip request to registered client)
For this purpose, I was trying to use "sipgo.NewClient" and "client.TransactionRequest" methods to do so. 
However, I was not able to initiate the same successfully. 

Can you provide some example code to achieve this?

Let me know if you need any more details from my side.

Thanks

**Comment by emiago** [comment]
Hi @p-akshay ,

I think you need watch out on couple things. First I am not clear how did you build your registration server, but consider 
if your client is behind NAT, then you also need to take care of that. 

When you are building client handle, wrap same `ua` as `server` to have access to same transport layer. 
I can not see any reason why client should fail, unless recipient is bad address. 
What you can always do is to enforce request destination by IP using 
`req.SetDestination`  
This way you skip dns and other SIP destination. 

Also use `sip.SIPDebug` to actually see where `TransportLayer` is trying to push your request on which IP. 

I hope this helps!

Thanks for using sipgo
