### ISSUE TITLE
API for handling Bye as a client

### ISSUE THREAD

**Issue by Sean-Der** [emiago/sipgo#73]
I don't believe anything exists today to handle Bye as a client. Would it be ok if I added this API? 

```
func (c *Client) OnBye(handler RequestHandler) {
```

**Comment by emiago** [comment]
Hi @Sean-Der 

There is already, you just need to use `Server` handle. 
UA is build from client and server. For receiving you use `Server`. 

Key point is that you pass same `UA` to both client and server when building. 

UA is one who keeps transport layer underneath.

**Comment by Sean-Der** [comment]
👍 I will switch my client usage to server

**Comment by Sean-Der** [comment]
For my own understanding, is it common for SIP clients to not ever get server initiated transactions from the server? 

Bye from a server seems common use case

**Comment by emiago** [comment]
hi @Sean-Der , in SIP it is more peer 2 peer . I think this go same for webrtc only maybe by **default** you expect to go both ways.
Server/Client is just way we like to identify who starts transaction or lets better say `Request Context`, and in RFC you can find this ClientTransaction vs ServerTransaction (different behavior underhood). So following that pattern you also see this in lib. This is mainly as you want to have some different control or acting, but also State changes differentely depending is your `Request Context` as client or as server.

For example  in case of `Proxy` you may want that your  proxy (server listener) receives request over TLS transport, but you may want to send on internal network to UDP transport. Still one side acts as server and second as client.

Spliting this I also find better for lib maintance and to align SIP RFC. And for example you can have single server listener and multiple clients to act differentely based on transport, IP they should use etc...

Anyway you can wrap `client` + `server` to act as some ` Peer` if your case is just dealing with Calls. 
 I try to intentionally call this as client vs server **handle** , but maybe this should go on code level as well.

In case of dialog I already added some `DialogClient` `DialogServer` wrappers to help, but you will see they need 
`client` and `server` for writing and reading. Again I am seperating them, as depending your `Request Context` you need to do different thing from client vs server during `dialog` setup.

I hope this helps, btw SIP RFC just has more than creating calls, it is used for more than dialog setup. Consider registration, pub/sub, messaging, notifications
