### ISSUE TITLE
register response  start line may split by LF

### ISSUE THREAD

**Issue by yushimeng** [emiago/sipgo#8]
Server may get sipVersion ends with LF if request start line ends with LF ranther than CRLF.
Although it's documented here.  https://www.rfc-editor.org/rfc/rfc3261.html#section-7 
If consider return err while startline ends with LF or CR ?
`
SIP/2.0
 200 OK
Via: SIP/2.0/UDP 192.168.10.8:60719;rport=60719;branch=z9hG4bK1377739937
From: <sip:34020000002000000719@3402000000>;tag=1534571172
To: <sip:34020000002000000719@3402000000>;tag=b70dda5e-f487-4b46-8e21-42b7c5dfcfa0
Call-ID: 1566767517
CSeq: 1 REGISTER
Content-Length: 0`

**Comment by emiago** [comment]
Hi @yushimeng Thx for contributing. 
Here I see there was some old code (unreachable) here left. I would need revisit this, but I think you are right. 
Could be some tests need to be updated as well.

**Comment by emiago** [comment]
Added fix. Pls check main branch

**Comment by emiago** [comment]
Considering this as fixed.
