### ISSUE TITLE
How to find the entire response event received in case of negative response to SIP INVITE

### ISSUE THREAD

**Issue by p-akshay** [emiago/sipgo#85]
Hello @emiago ,

currently, when I initiate the INVITE and then wait for response via dialog.WaitAnswer, I can analyze the response if I get 2xx response via dialog.InviteResponse

However, if the response is 403, we get the Error as "Invite failed with response: SIP/2.0 403 Forbidden".
In this case dialog.InviteResponse is set to "nil"
I would like to analyze the 403 response event as well to check the other headers involved.

Is there a way to achieve this part?

Do let me know if you need any more info from my side.

Thanks

**Comment by emiago** [comment]
Hi @p-akshay .

Cast to the error `ErrDialogResponse` . It has response inside

**Comment by p-akshay** [comment]
Hi @emiago ,

I tried to typecast the error. However, the compiler is throwing a "type assertion error" while compiling.

here is my relevant code:

`errDlg := dialog.WaitAnswer(ctx, sipgo.AnswerOptions{})
if errDlg != nil {
   fmt.Printf("%+v\n", sipgo.ErrDialogResponse(errDlg)
}`

I also tried to directly cast the err to `ErrDialogResponse`, however, the same compile error was there.

I guess, I am missing something really easy fix here. 
Please let me know the changes that I need to add here.

Thanks

**Comment by emiago** [comment]
@p-akshay sorry not casting, I meant interface assertion. 
You have `errors.As` . I think you can find some go example

**Comment by p-akshay** [comment]
@emiago ,

Thanks...It is working now
