### ISSUE TITLE
Request BYE returned 500 Invalid CSeq

### ISSUE THREAD

**Issue by muchlisegeroo** [emiago/sipgo#90]
Hi,

This happened when call hangup process, the SIP response sent by the server got 500 Invalid CSeq.
<img width="1288" alt="Screenshot 2024-05-17 at 10 52 42" src="https://github.com/emiago/sipgo/assets/157561085/86c7ab84-12ef-4ab6-9eae-40571c598d82">

I think this is because when the digest auth request is sent, the last CSeq header is not saved, so the next request will still use the old one.
<img width="1331" alt="Screenshot 2024-05-17 at 10 54 09" src="https://github.com/emiago/sipgo/assets/157561085/4daa05f7-1df1-4af3-ad45-cda730c2c323">

i use sipgox@v0.8.1 and sipgo@v0.21.0

**Comment by emiago** [comment]
Thanks for reporting. 
Can you tell me are you using sigpox.Phone or what is your flow

**Comment by muchlisegeroo** [comment]
Yes, I'm using sipgox.Phone for dialing and this happened when calling phone.Hangup().

I have tried to do it this way and it does work, but I have no idea if it is the right way.
<img width="1004" alt="Screenshot 2024-05-18 at 05 30 15" src="https://github.com/emiago/sipgo/assets/157561085/d4848280-f51c-4393-a60d-b4907bb05eb1">

**Comment by emiago** [comment]
hi @muchlisegeroo there is now refactored code on sipgo to handle more correctly Dialog request. 
one of is CSEQ. I probably have not ported this. 

So there is RFC for dialog generaly. You have `dialog.TransactionRequest` This should be used for now when dealing with request within dialog. 
This will correctly follow CSEQ and other. 

Thanks for reporting, I will have to move auth to this. pls wait for fix

**Comment by muchlisegeroo** [comment]
Ok, great. Thanks.

**Comment by emiago** [comment]
@muchlisegeroo can you pls checkout latest commits on sipgox and see is issue resolved for you. 
Now auth should travel as well through `dialog.TransactionRequest`

If not resolved. pls reopen
