### ISSUE TITLE
Could you provide a client-side example, with TCP long connection

### ISSUE THREAD

**Issue by duiniuluantanqin** [emiago/sipgo#95]
Could you provide me with a client-side example to achieve the following functionality?

1. The client actively connects to the server (another remote host) via the TCP protocol. 
2. Once the connection is established successfully, it sends a REGISTER message proactively and maintains this TCP long connection. 
3. It can then receive INVITE, BYE, MESSAGE, and other messages sent actively by the remote party and respond accordingly.

**Comment by emiago** [comment]
hi @duiniuluantanqin . There is some example for register in repo, but for you problem
you only need to setup this 
https://github.com/emiago/sipgo/blob/main/sip/transport.go#L16

Anyway by default sipgo is keeping connection open as long they are referenced. in other words as long you have active transactions (NOT terminated). 

On other hand you have all that covered on `sipgox.Phone` with `Answer`.  So checkout https://github.com/emiago/sipgox repo

You only have one line to call and voilaa. HINT: it works only for single CALL.

Feel free to reopen issue if you need more details

**Comment by duiniuluantanqin** [comment]
Thank you very much for your response.
However, I have another question regarding the third point mentioned above. I want to implement a Client (A) that connects to a Server (B) via the TCP protocol.
By calling `ClientRequestConnection`, I can obtain a socket connection, such as `conn Connection`.
Now, I would like to set some callback events for `conn`, such as `OnInvite`, `OnBye`, `OnMessage`. How can this be achieved?
