### ISSUE TITLE
miss route headers in UAS BYE request

### ISSUE THREAD

**Issue by hateeyan** [emiago/sipgo#97]
I found that there is no route headers in UAS BYE request.

It was removed in this [commit](https://github.com/emiago/sipgo/commit/2d4a8a193780aa4df35990c4be4e990e4835f60b#diff-f69cd8462628ad4c37f6ed09bf1a15c8b5d986b617f4a44d44b371dd14ddbfd3L343-L349), is this a bug or is there some other reason?

![image](https://github.com/emiago/sipgo/assets/42289672/97811c79-3010-4372-906b-45042832ebd2)

![image](https://github.com/emiago/sipgo/assets/42289672/2d472ed6-c68b-48f3-bf06-8f7b31bff229)

**Comment by emiago** [comment]
yeah I see bug. Thanks for reporting

**Comment by emiago** [comment]
@hateeyan Check the latest main branch

**Comment by hateeyan** [comment]
@emiago Thanks, it works fine!
